@echo off
echo Starting VayuRoute Edge Backend and Frontend...
start cmd /k "call venv\Scripts\activate && cd backend && uvicorn main:app --host 127.0.0.1 --port 8000"
start cmd /k "cd frontend && npm run dev"
echo Servers are launching...
